spring:
  application:
    name: archimedes-example

server:
  port: 8080

archimedes:
  api:
    enabled: true
    ui-enabled: true
    base-path: /archimedes
    base-packages:
      - io.github.nianliu.archimedes.example

logging:
  level:
    io.github.nianliu.archimedes: DEBUG
